### ISSUE TITLE
sweet!

### ISSUE THREAD

**Issue by rvanderwerf** [frogermcs/Google-Actions-Java-SDK#1]
Hi I came across your project. Thanks for making this, I was just looking to make something similar and glad you already ported the sdk! I had a couple questions for you. I was able to deploy your sample app as a war and get an initial response from it. However I'm not sure how to ask it how to repeat something to invoke the text handler - it seems to say back 'Your query is handled by Google’s system actions' if I enter anything. Do you know the proper syntax for the sample to get it to repeat back something from the ask Response? I'm new to google actions, but I have been doing Alexa skills kit stuff with Java and Groovy for quite a while so the concepts I am familiar with.:

I start with:
talk to testAgent (the name of my agent) - works good
talk to testAgent something back - get error
also tried at testAgent 'something' - error
 
I am sure I missing something obvious here... not sure if you are on any slack or irc channels that might be a better question to ask this kind of stuff?

Thanks,

Ryan

**Comment by rvanderwerf** [comment]
scratch that I got it to repeat back.. I just have to be careful of the words I use. You don't have the sdk jar uploaded anywhere like bintray or mavencental correct? I can put it in my bintray account for now.

**Comment by frogermcs** [comment]
Hey @rvanderwerf ! Yeah, thanks for pointing this. I'm finally pushing it to jCenter, so library will be available as:  

`com.frogermcs.gactions:gactions:0.1.1`
